experiment_name: "EXP1_SIMPLE_RGB"

data:
  dataset: "cornell"
  root_dir: "data/cornell"   # ajusta si tu ruta real es otra
  img_size: 224
  use_rgb: true
  use_depth: false
  val_split: 0.2

model:
  name: "simple_cnn"
  in_channels: 3      # RGB => 3 canales
  num_outputs: 5

train:
  batch_size: 32
  num_epochs: 10
  lr: 0.001
  weight_decay: 0.0
  num_workers: 4
  device: "cpu"       # si luego quieres, lo cambias a "cuda"

logging:
  base_dir: "experiments"
  ckpt_dirname: "checkpoints"
  metrics_filename: "metrics.csv"

metrics:
  iou_thresh: 0.25        # umbral estándar Cornell
  angle_thresh: 30.0  # umbral típico en grados
