experiment:
  name: "EXP2_SIMPLE_RGBD"

data:
  dataset: "cornell"
  root_dir: "data/cornell"
  img_size: 224
  use_rgb: true
  use_depth: true  # aquí activas depth
  val_split: 0.2

model:
  name: "simple_cnn"
  in_channels: 4   # RGB-D => 4 canales
  num_outputs: 5

train:
  batch_size: 32
  num_epochs: 10
  lr: 1e-3
  num_workers: 4
  device: "cpu"
